USE TaskManager

IF NOT EXISTS(SELECT * FROM SYS.TABLES WHERE NAME = 'GRUPO_ATIVIDADE')
BEGIN

	CREATE TABLE GRUPO_ATIVIDADE
	(
		GPA_Tid INTEGER NOT NULL IDENTITY,
		GPA_Descricao VARCHAR(20) NOT NULL,
		GPA_Observacao VARCHAR(300),
		GPA_Ativo BIT,
		PRIMARY KEY (GPA_Tid)
	)

END
ELSE
BEGIN

	SELECT 'Já existe a tabela GRUPO_ATIVIDADE no banco de dados' as Retorno

END