USE TaskManager

IF NOT EXISTS(SELECT * FROM SYS.TABLES WHERE NAME = 'STATUS_ATIVIDADE')
BEGIN

	CREATE TABLE STATUS_ATIVIDADE
	(
		SAT_Tid INTEGER NOT NULL IDENTITY,
		SAT_Descricao VARCHAR(50) NOT NULL,
		PRIMARY KEY(SAT_Tid)
	)

END
ELSE
BEGIN

	SELECT 'Já existe a tabela STATUS_ATIVIDADE no banco de dados' as Retorno

END