USE TaskManager

IF NOT EXISTS(SELECT * FROM SYS.TABLES WHERE NAME = 'PERFIL_USUARIO')
BEGIN

	CREATE TABLE PERFIL_USUARIO
	(
		PFU_Tid INTEGER NOT NULL IDENTITY,
		PFU_Nome VARCHAR(20) NOT NULL,
		PFU_Ativo BIT,
		PRIMARY KEY(PFU_Tid)
	)

END
ELSE
BEGIN

	SELECT 'Já existe a tabela PERFIL_USUARIO no banco de dados' as Retorno

END