IF NOT EXISTS(SELECT * FROM SYS.TABLES WHERE NAME = 'USUARIO')
BEGIN

	CREATE TABLE USUARIO
	(
		USU_Tid INTEGER NOT NULL IDENTITY,
		USU_Nome VARCHAR(50) NOT NULL,
		USU_Login VARCHAR(20) NOT NULL,
		USU_Senha VARBINARY(100),
		USU_Ativo BIT,
		USU_PFU_TidPerfilUsuario INTEGER,
		PRIMARY KEY (USU_Tid),
		FOREIGN KEY (USU_PFU_TidPerfilUsuario) REFERENCES PERFIL_USUARIO(PFU_Tid) 
	)

END
ELSE
BEGIN

	SELECT 'Já existe a tabela USUARIO no banco de dados' as Retorno

END