IF NOT EXISTS(SELECT * FROM SYS.TABLES WHERE NAME = 'ATIVIDADE')
BEGIN

	CREATE TABLE ATIVIDADE
	(
		ATV_Tid INTEGER NOT NULL IDENTITY,
		ATV_GPA_TidGrupoAtividade INTEGER,
		ATV_TPA_TidTipoAtividade INTEGER,
		ATV_USU_TidUsuarioAtividade INTEGER,
		ATV_Descricao VARCHAR(100) NOT NULL,
		ATV_DataHoraCadastro DATETIME,
		ATV_DataHoraInicio DATETIME,
		ATV_DataHoraPausa DATETIME,
		ATV_DataHoraConclusao DATETIME,
		ATV_SAT_TidStatusAtividade INTEGER,
		ATV_TempoTotal TIME,
		ATV_DataHoraReinicio DATETIME,
		ATV_CodigoReferencia INTEGER,
		PRIMARY KEY(ATV_Tid),
		FOREIGN KEY(ATV_GPA_TidGrupoAtividade) REFERENCES GRUPO_ATIVIDADE(GPA_Tid),
		FOREIGN KEY(ATV_TPA_TidTipoAtividade) REFERENCES TIPO_ATIVIDADE(TPA_Tid),
		FOREIGN KEY(ATV_USU_TidUsuarioAtividade) REFERENCES USUARIO(USU_Tid),
		FOREIGN KEY(ATV_SAT_TidStatusAtividade) REFERENCES STATUS_ATIVIDADE(SAT_Tid)
	)

END
ELSE
BEGIN

	SELECT 'Já existe a tabela ATIVIDADE no banco de dados' as Retorno

END