IF NOT EXISTS(SELECT * FROM SYS.TABLES WHERE NAME = 'LOG_ATIVIDADE')
BEGIN

	CREATE TABLE LOG_ATIVIDADE
	(
		LGA_Tid INTEGER NOT NULL IDENTITY,
		LGA_ATV_TidAtividade INTEGER NOT NULL,
		LGA_USU_TidUsuario INTEGER NOT NULL,
		LGA_DataHoraCadastro DATETIME NOT NULL,
		LGA_Observacao VARCHAR(MAX),
		PRIMARY KEY(LGA_Tid),
		FOREIGN KEY(LGA_ATV_TidAtividade) REFERENCES ATIVIDADE(ATV_Tid),
		FOREIGN KEY(LGA_USU_TidUsuario) REFERENCES USUARIO(USU_Tid)
	)

END
ELSE
BEGIN

	SELECT 'Já existe a tabela LOG_ATIVIDADE no banco de dados' as Retorno

END