IF NOT EXISTS(SELECT * FROM SYS.TABLES WHERE NAME = 'LOG_ERRO')
BEGIN

	CREATE TABLE LOG_ERRO
	(
		LER_Tid INTEGER NOT NULL IDENTITY,
		LER_DataErro DATETIME NOT NULL,
		LER_DescricaoErro VARCHAR(MAX),
		LER_ProcedureErro VARCHAR(MAX),
		PRIMARY KEY(LER_Tid)
	)

END
ELSE
BEGIN

	SELECT 'Já existe a tabela LOG_ERRO no banco de dados' as Retorno

END