IF NOT EXISTS(SELECT * FROM SYS.TABLES WHERE NAME = 'USUARIO_TEMPO_DIA')
BEGIN

	CREATE TABLE USUARIO_TEMPO_DIA
	(
		UTD_Tid INTEGER NOT NULL IDENTITY,
		UTD_USU_TidUsuario INTEGER NOT NULL,
		UTD_DataAtividade DATETIME,
		UTD_TempoTotalDia TIME,
		PRIMARY KEY(UTD_Tid),
		FOREIGN KEY(UTD_USU_TidUsuario) REFERENCES USUARIO(USU_Tid)
	)

END
ELSE
BEGIN

	SELECT 'Já existe a tabela USUARIO_TEMPO_DIA no banco de dados' as Retorno

END